# -*- coding: utf-8 -*-
"""Python_Workshop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cUnpXvvjqOINqDH0OnFJvV8hBCPiRbAP
"""

import pandas as pd

df = pd.read_csv('insurance.csv')
df

df['sex'] = df['sex'].replace({'female': 'Female', 'male': 'Male'})
df

df['bmi'] = df['bmi'].round(2)
df

df['smoker'] = df['smoker'].replace({'yes': 'Yes', 'no': 'No'})
df

df['region'] = df['region'].replace({'southwest': 'Southwest', 'northwest': 'Northwest','southeast': 'Southeast', 'northeast': 'Northeast'})
df

df['charges'] = df['charges'].round(2)
df

import numpy as np
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
for col in ['sex','smoker','region']:
  df[col] = le.fit_transform(df[col])
df

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

x = df.drop(columns = ['smoker', 'region'])
y = df['smoker']

model = RandomForestClassifier(random_state=42)
model.fit(x,y)
y_pred = model.predict(x)

print('Accuracy:' , accuracy_score(y, y_pred))
print('\nClassification Report:\n', classification_report(y, y_pred))
print('\nConfusion Matrix:\n', confusion_matrix(y, y_pred))